# Generated by Django 3.0.5 on 2020-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=20)),
                ('Institute', models.CharField(default='', max_length=50)),
                ('SubUrb', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
