# Generated by Django 3.0.5 on 2020-05-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userRegistration', '0002_newbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
