# Generated by Django 3.0.5 on 2020-05-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0003_auto_20200505_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='BookOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='userRegistration.UserPersonalInfo'),
            preserve_default=False,
        ),
    ]
