# Generated by Django 3.0.5 on 2020-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_newbook_bookowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='Tag3',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5'), ('Sem6', 'Sem6'), ('Sem7', 'Sem7'), ('Sem8', 'Sem8')], default='', max_length=15),
        ),
    ]
