# Generated by Django 3.0.5 on 2020-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0005_newbook_tag3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbook',
            name='Tag3',
        ),
        migrations.AlterField(
            model_name='newbook',
            name='Tag1',
            field=models.CharField(choices=[('First Year', 'First Year'), ('CSE', 'CSE'), ('IT', 'IT'), ('Entc', 'Entc'), ('Mech', 'Mech'), ('Instrumentation', 'Instrumentation'), ('Production', 'Production'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechatronix', 'Mechatronix')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newbook',
            name='Tag2',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5'), ('Sem6', 'Sem6'), ('Sem7', 'Sem7'), ('Sem8', 'Sem8')], default='', max_length=15),
        ),
    ]
