# Generated by Django 3.0.5 on 2020-05-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_auto_20200507_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalcPic', models.ImageField(blank=True, upload_to='books')),
                ('price', models.IntegerField(default=0)),
                ('modelName', models.CharField(max_length=20)),
                ('CalcOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CalcOwner', to='userRegistration.UserPersonalInfo')),
            ],
        ),
    ]
