# Generated by Django 3.0.5 on 2020-05-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0009_workshopuniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopuniform',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
