# Generated by Django 3.0.5 on 2020-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0010_workshopuniform_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='books')),
                ('Name', models.CharField(max_length=40)),
                ('Branch', models.CharField(choices=[('All', 'All'), ('First Year', 'First Year'), ('CSE', 'CSE'), ('IT', 'IT'), ('Entc', 'Entc'), ('Mech', 'Mech'), ('Instrumentation', 'Instrumentation'), ('Production', 'Production'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechatronix', 'Mechatronix')], max_length=40)),
                ('Semister', models.CharField(choices=[('All', 'All'), ('First Year', 'First Year'), ('CSE', 'CSE'), ('IT', 'IT'), ('Entc', 'Entc'), ('Mech', 'Mech'), ('Instrumentation', 'Instrumentation'), ('Production', 'Production'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechatronix', 'Mechatronix')], max_length=40)),
                ('Type', models.CharField(choices=[('All', 'All'), ('First Year', 'First Year'), ('CSE', 'CSE'), ('IT', 'IT'), ('Entc', 'Entc'), ('Mech', 'Mech'), ('Instrumentation', 'Instrumentation'), ('Production', 'Production'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechatronix', 'Mechatronix')], max_length=40)),
                ('Unit', models.CharField(choices=[('All', 'All'), ('First Year', 'First Year'), ('CSE', 'CSE'), ('IT', 'IT'), ('Entc', 'Entc'), ('Mech', 'Mech'), ('Instrumentation', 'Instrumentation'), ('Production', 'Production'), ('Chemical', 'Chemical'), ('Electrical', 'Electrical'), ('Mechatronix', 'Mechatronix')], max_length=40)),
            ],
        ),
    ]
