# Generated by Django 3.0.5 on 2020-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0011_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Semister',
            field=models.CharField(choices=[('None', 'None'), ('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Sem3', 'Sem3'), ('Sem4', 'Sem4'), ('Sem5', 'Sem5'), ('Sem6', 'Sem6'), ('Sem7', 'Sem7'), ('Sem8', 'Sem8')], max_length=40),
        ),
        migrations.AlterField(
            model_name='file',
            name='Type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Q-paper', 'Q-paper'), ('Notes', 'Notes'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='file',
            name='Unit',
            field=models.CharField(choices=[('None', 'None'), ('All', 'All'), ('Unit-1', 'Unit-1'), ('Unit-2', 'Unit-2'), ('Unit-3', 'Unit-3'), ('Unit-4', 'Unit-4'), ('Unit-5', 'Unit-5'), ('Unit-6', 'Unit-6')], max_length=40),
        ),
    ]
