# Generated by Django 3.0.5 on 2020-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0012_auto_20200509_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(max_length=200, upload_to='books'),
        ),
    ]
