# Generated by Django 3.0.5 on 2020-05-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0013_auto_20200509_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Name',
            new_name='Subject_and_Topic',
        ),
    ]
